sudo: required
services:
  - docker

before_install:
  - docker build -t zeepeebee30/multi-cont-app -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true zeepeebee30/multi-cont-app npm test

after_success:
  - docker build -t zeepeebee30/multi-client ./client
  - docker build -t zeepeebee30/multi-nginx ./nginx
  - docker build -t zeepeebee30/multi-server ./server
  - docker build -t zeepeebee30/multi-worker ./worker
# Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push zeepeebee30/multi-client
  - docker push zeepeebee30/multi-nginx
  - docker push zeepeebee30/multi-server
  - docker push zeepeebee30/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-390648466963"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
